export const ErrorCodes = {
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
    INVALID_INPUT: "INVALID_INPUT",
    NOT_FOUND: "NOT_FOUND",

    BOOKING_CONFLICT: "BOOKING_CONFLICT",
    BOOKING_NOT_FOUND: "BOOKING_NOT_FOUND",
    USER_NOT_FOUND: "USER_NOT_FOUND",
    CAR_NOT_FOUND: "CAR_NOT_FOUND",
    CAR_NOT_AVAILABLE: "CAR_NOT_AVAILABLE",
    START_DATE_AFTER_END_DATE: "START_DATE_AFTER_END_DATE",

    CAR_ALREADY_EXISTS: "CAR_ALREADY_EXISTS",
};
